c=-(1/2)+(pi/6)*i;
c1=0+(pi/6)*i;
c2=(1/2)+(pi/6)*i;
k=2;
n=0:40;
x=k*exp(c*n);
x1=k*exp(c1*n);
x2=k*exp(c2*n);
subplot(3,2,1);
stem(n,real(x));
xlabel('Time Index n');
ylabel('Amplitude');
title('Real part with SIGMA<0');
subplot(3,2,2);
stem(n,imag(x));
xlabel('Time Index n');
ylabel('Amplitude');
title('Imaginary part with SIGMA<0');
subplot(3,2,3);
stem(n,real(x1));
xlabel('Time Index n');
ylabel('Amplitude');
title('Real part with SIGMA=0');
subplot(3,2,4);
stem(n,imag(x1));
xlabel('Time Index n');
ylabel('Amplitude');
title('Imaginary part with SIGMA=0');
subplot(3,2,5);
stem(n,real(x2));
xlabel('Time Index n');
ylabel('Amplitude');
title('Real part with SIGMA>0');
subplot(3,2,6);
stem(n,imag(x2));
xlabel('Time Index n');
ylabel('Amplitude');
title('Imaginary part with SIGMA>0');